version: '3'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - "db"
    environment:
      MIX_ENV: docker
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ex_vote_dev
