version: '3'
services:
  web:
    build: .
    ports:
      - "9750:9750"
    depends_on:
      - "db"
    environment:
      MIX_ENV: docker
      EXVOTE_PORT: 9750
      EXVOTE_PATH: /
      EXVOTE_HOST: localhost
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ex_vote_dev
